# API設定
[api]
openai_key = "" # OpenAIのAPIキー
google_key = "" # Google Cloud Vision APIのAPIキー
claude_key = "" # anthropicのAPIキー

# Hugging Face設定
[huggingface]
hf_username = "" # Hugging Faceのユーザー名
repo_name = "" # リポジトリ名
token = "" # Hugging FaceのAPIトークン

# ディレクトリ設定
[directories]
database = ""  # 画像databaseのパス (空の場合はカレントディレクトリの'Image_database.image_database.db'を使用)
dataset = ""  # 画像ディレクトリのパス
output = ""   # 出力ディレクトリのパス（空の場合はカレントディレクトリの'output'を使用）
edited_output = ""  # 編集済みデータセットのパス（空の場合はカレントディレクトリの'edited_output'を使用）
response_file = ""  # レスポンスファイルディレクトリのパス（空の場合はカレントディレクトリの'response_file'を使用）

# 画像処理設定
[image_processing]
target_resolution = 512 # 学習モデルの基準解像度 512, 768, 1024
realesrganer_upscale = false # 長編が基準解像度より小さい場合、Trueだとアップスケールする
realesrgan_model = "RealESRGAN_x4plus_anime_6B.pth" # アップスケールモデルのパス

# 生成設定
[generation]
batch_jsonl = false # バッチ処理用のjsonlファイルを生成する場合はTrue
start_batch = false # バッチ処理を開始する場合はTrue
single_image = true # 画像ごとに処理する場合はTrue

# オプション設定
[options]
generate_meta_clean = false # sd-scriptsのファインチューニング用のメタデータを生成する場合はTrue
cleanup_existing_tags = false # タグを生成せずに既存のタグをクーんナップする場合はTrue
join_existing_txt = true # 生成したタグを既存のタグと結合する場合はTrue

# プロンプト設定
[prompts]
additional = "Your additional prompt here."

[log]
level = "INFO"
file = "app.log"